#!/usr/bin/env bash
# Write infra/compose.env for Docker Compose project interpolation only.
# Secrets stay in .env and are passed to api/worker via env_file (literal).
# Using a narrow env file avoids Compose expanding "$" inside COOKIE_ENCRYPTION_SEED
# / SECRET_KEY (warnings like: The "G" variable is not set).
#
# Usage: write-compose-env.sh [app-dir]
set -euo pipefail

APP_DIR="${1:-.}"
cd "$APP_DIR"

_env_val() {
  grep -E "^${1}=" .env 2>/dev/null | head -1 | cut -d= -f2- || true
}

DOMAIN="${DOMAIN:-$(_env_val DOMAIN)}"
ACME_EMAIL="${ACME_EMAIL:-$(_env_val ACME_EMAIL)}"
# Caller IMAGE_TAG wins; else .env; else latest.
if [[ -z "${IMAGE_TAG:-}" ]]; then
  IMAGE_TAG="$(_env_val IMAGE_TAG)"
fi
IMAGE_TAG="${IMAGE_TAG:-latest}"
if [[ -z "${GHCR_OWNER:-}" ]]; then
  GHCR_OWNER="$(_env_val GHCR_OWNER)"
fi
GHCR_OWNER="${GHCR_OWNER:-commercialbrainz}"

OUT="infra/compose.env"
mkdir -p infra
cat > "$OUT" <<EOF
# Auto-generated — docker compose --env-file (not secrets).
# Regenerated by fix-gcloud-vm.sh / vm-startup.sh.
IMAGE_TAG=${IMAGE_TAG}
GHCR_OWNER=${GHCR_OWNER}
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
EOF

# Compose always auto-loads <project-dir>/.env for interpolation. When we use
# --project-directory infra, keep infra/.env identical to compose.env so root
# .env secrets (with "$") are never interpolated → no "G" / "mcpX" warnings.
cp "$OUT" infra/.env

echo "Wrote $OUT and infra/.env (IMAGE_TAG=${IMAGE_TAG} GHCR_OWNER=${GHCR_OWNER} DOMAIN=${DOMAIN:-none})"
